[package]
name = "discordbot_rust"
version = "0.1.0"
authors = ["El-Chapo0133 <levequeloris66@gmail.com>"]
edition = "2018"


[dependencies]
futures-macro = "0.3.5"
serenity = "0.8"
serde = "1.0.100"
serde_json = "1.0"
time = "0.1.43"

[[bin]]
name = "discordbot_rust"
path = "main.rs"